image: python:3.7-alpine

before_script:
- apk update
- apk add doxygen
## Uncomment the following line if you use graphviz dot graphs
#- apk add ttf-freefont graphviz

test:
  stage: test
  script:
  - pip install -U sphinx
  - sphinx-build -b html . public
#  only:
#  - branches
#  except:
#  - master

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - cd docs_sphinx
  - sphinx-build -b html . public
  artifacts:
    paths:
    - public
  only:
  - master
