image: python:3.7-alpine

test:
  stage: test
  script:
  - apt-get install doxygen
  - pip install -U sphinx
  - cd docs_sphinx
  - sphinx-build -b html . public
  only:
  - branches
  except:
  - master

pages:
  stage: test
  script:
  - apt-get install doxygen
  - pip install -U sphinx
  - cd docs_sphinx
  - sphinx-build -b html . public
  artifacts:
    paths:
    - public
  only:
  - master
