
name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup virtual environment
      run: |
        pip install --upgrade pip
        python3.8 -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
    - name: Install Cmake
      run: >-
        sudo apt-get install cmake
    - name: check directory content
      run: |
        cd env/lib
        ls
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Install cibuildwheel
      run: |
        ls 
        source env/bin/activate
        python -m pip install cibuildwheel==2.4.0
        
    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: 1.77.0
        boost_install_dir: ${{ matrix.boost_install_dir }}
    - name: Check directory
      run:  ls boost/boost
    - name: Build a binary wheel and a source tarball
      uses: pypa/cibuildwheel@v2.4.0
      env:
        CIBW_BUILD: "cp38-*"
        CIBW_SKIP: "*-win32 *-musllinux_x86_64 *_i686"        
        CIBW_BEFORE_BUILD: python -m pip install cmake
        CIBW_BEFORE_BUILD_LINUX: echo $BOOST_ROOT
        CIBW_BEFORE_ALL_LINUX: >-
          sudo apt-get update
        CIBW_ENVIRONMENT: BOOST_ROOT=boost/boost-1.77.0-ubuntu-18.04
        CIBW_ENVIRONMENT_LINUX: BOOST_ROOT=/boost/boost-1.77.0-ubuntu-18.04
        CIBW_ENVIRONMENT_WINDOWS: BOOST_ROOT_PIPELINE=/boost/boost-1.77.0-ubuntu-18.04          
        CIBW_ENVIRONMENT_PASS_LINUX: /boost/boost-1.77.0-ubuntu-18.04
          
    - name: check directory content
      run: |
        ls
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
