name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup virtual environment
      run: |
        pip install --upgrade pip
        python3.8 -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
    - name: Install Cmake
      run: >-
        sudo apt-get install cmake
    - name: Install Boost
      run: >-
        sudo apt-get install libboost-all-dev

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build SDist
      run: python -m build --sdist

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz
        
  build_wheels:
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - uses: pypa/cibuildwheel@v2.4.0

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl
        
  upload_all:
    needs: [build-n-publish, build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
